version: "3.9"
services:
  postgres:
    image: postgres:11
    ports: 
        - "5433:5432"
    environment:
        POSTGRES_PASSWORD: mysecretpassword
        POSTGRES_USER: postgres
    volumes: 
            - ./postgres_data:/var/lib/postgresql/data
  server:
    build: ./server
    command: bash -c "rm -f tmp/pids/server.pid &&  rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./server:/spotcode
    ports:
      - "3000:3000"
    depends_on:
      - postgres